src/cart/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import CartListView, CartDeleteView

app_name = 'cart'
urlpatterns = [
    path(
        '',
        login_required(CartListView.as_view()),
        name='cart_list_view'
    ),
    path(
        '<int:pk>/delete/',
        login_required(CartDeleteView.as_view()),
        name='cart_item_delete_view'
    )
]

src/djecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('users/', include('users.urls')),
    path('profiles/', include('profiles.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    AddToCartView,
    ProductDeleteView,
    ProductLikeView,
    ProductUnLikeView
)

app_name = 'products'
urlpatterns = [
    path(
        '',
        ProductListView.as_view(),
        name='product_list_view'
    ),
    path(
        'create/',
        ProductCreateView.as_view(),
        name='product_create_view'
    ),
    path(
        '<int:pk>/details',
        ProductDetailView.as_view(),
        name='product_details_view'
    ),
    path(
        '<int:pk>/update',
        ProductUpdateView.as_view(),
        name='product_update_view'
    ),
    path(
        '<int:pk>/like',
        login_required(ProductLikeView.as_view()),
        name='product_like_view'
    ),
    path(
        '<int:pk>/unlike',
        login_required(ProductUnLikeView.as_view()),
        name='product_unlike_view'
    ),
    path(
        '<int:pk>/cart/add',
        login_required(AddToCartView.as_view()),
        name='product_add_to_cart_view'
    ),
    path(
        '<int:pk>/delete',
        ProductDeleteView.as_view(),
        name='product_delete_view'
    )
]

src/products/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class Product(models.Model):
    name = models.CharField(
      max_length=100
    )
    price = models.DecimalField(
      max_digits=1000,
      decimal_places=2
    )
    description = models.TextField(
      default="It's awesome product..",
      blank=True,
      null=True
    )
    provide_by = models.CharField(
      max_length=120,
      default='King Pro Pvt Ltd'
    )
    published_at = models.DateTimeField(
      auto_now_add=True
    )
    image = models.ImageField(
      upload_to='product_images'
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self, *args, **kwargs):
        return reverse(
          'products:product_details_view',
          kwargs={'pk': self.id}
        )

    def get_edit_url(self, *args, **kwargs):
        return reverse(
          'products:product_update_view',
          kwargs={'pk': self.id}
        )

    def get_like_url(self, *args, **kwargs):
        return reverse(
          'products:product_like_view',
          kwargs={'pk': self.id}
        )

    def get_unlike_url(self, *args, **kwargs):
        return reverse(
          'products:product_unlike_view',
          kwargs={'pk': self.id}
        )

    def get_add_to_cart_url(self, *args, **kwargs):
        return reverse(
          'products:product_add_to_cart_view',
          kwargs={'pk': self.id}
        )

class LikeManager(models.Manager):
  def get_like(self, user, product, *args, **kwargs):
    return self.filter(user=user, product=product)

  def create_like(self, user, product, *args, **kwargs):
    like = self.create(user=user, product=product)
    return like.save()

class Like(models.Model):
    user = models.ForeignKey(
      settings.AUTH_USER_MODEL,
      default=1,
      on_delete=models.CASCADE
    )
    product = models.ForeignKey(
      Product,
      default=1,
      on_delete=models.CASCADE
    )
    liked_at = models.DateTimeField(
      auto_now_add=True
    )

    objects = LikeManager()

src/products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

src/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.views.generic import (
	View,
	ListView,
	DetailView,
	CreateView,
	UpdateView,
	DeleteView
)
from django.contrib import messages
from django.http import Http404

from .models import Product, Like
from cart.models import Cart

from .forms import ProductForm
from cart.forms import CartForm


# List out all products
class ProductListView(ListView):
	queryset = Product.objects.all()
	context_object_name = 'products'

	def get_context_data(self, **kwargs):
		context = super(ProductListView, self).get_context_data(**kwargs)
		context['title'] = 'Products'
		return context


# Products details view
class ProductDetailView(DetailView):
	queryset = Product.objects.all()
	context_object_name = 'product'

	def get_context_data(self, **kwargs):
		context = super(ProductDetailView, self).get_context_data(**kwargs)
		context['title'] = 'Product Details'
		return context


# Product create view
class ProductCreateView(CreateView):
	queryset = Product.objects.all()
	template_name = 'products/product_create.html'
	form_class = ProductForm

	def form_valid(self, form):
		return super(ProductCreateView, self).form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(ProductCreateView, self).get_context_data(**kwargs)
		context['title'] = 'Product Create'
		return context


# Product update view
class ProductUpdateView(UpdateView):
	queryset = Product.objects.all()
	template_name = 'products/product_update.html'
	form_class = ProductForm

	def form_valid(self, form):
		messages.success(self.request, 'Product has been updated successfully!')
		print(form.cleaned_data)
		return super(ProductUpdateView, self).form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(ProductUpdateView, self).get_context_data(**kwargs)
		context['title'] = 'Product Update'
		return context


# Product Add To Cart View
class AddToCartView(View):
	def get_object(self):
		product_id = self.kwargs.get('pk')
		return get_object_or_404(Product, pk=product_id)

	def get(self, request, pk=None, *args, **kwargs):
		form = CartForm()
		context = {
			'form': form,
			'product': self.get_object()
		}
		return render(request, 'products/product_add_to_cart.html', context)

	def post(self, request, pk=None, *args,**kwargs):
		form = CartForm(request.POST)
		if form.is_valid():
			try:
				item = Cart.objects.get_cart_item(self.get_object(), request.user)
				if item:
					messages.error(request, 'Item is already in your cart!')
					return redirect('/products')
			except Cart.DoesNotExist:
				item = form.save(commit=False)
				item.product = self.get_object()
				item.user = request.user
				form.save()
				messages.success(request, 'Item has been added to your cart!')
				return redirect('/products')


# Product delete view
class ProductDeleteView(DeleteView):
	queryset = Product.objects.all()
	template_name = 'products/product_delete.html'
	context_object_name = 'product'
	success_url = '/products'

	def get_context_data(self, **kwargs):
		context = super(ProductDeleteView, self).get_context_data(**kwargs)
		context['title'] = 'Product Delete'
		return context


# Product Like View
class ProductLikeView(View):
	def get_object(self):
		id = self.kwargs.get('pk')
		return get_object_or_404(Product, pk=id)
	
	def get(self, request, pk=None, *args, **kwargs):
		is_liked = Like.objects.get_like(request.user, self.get_object())
		if is_liked:
			messages.error(request, 'Product has already been liked!')
			return redirect('/products')
		like = Like.objects.create_like(request.user, self.get_object())
		messages.success(request, 'Product has been liked!')
		return redirect('/products')


# Product Like View
class ProductUnLikeView(View):
	def get_object(self):
		id = self.kwargs.get('pk')
		return get_object_or_404(Product, pk=id)
	
	def get(self, request, pk=None, *args, **kwargs):
		is_liked = Like.objects.get_like(request.user, self.get_object())
		if is_liked:
			is_liked.delete()
			messages.success(request, 'Product has been unliked!')
			return redirect('/products')
		messages.error(request, 'Product has not been liked!')
		return redirect('/products')
	

src/products/templates/products/product_add_to_cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<header class="mb-5">
  <h3 style="font-weight: bold" class="page-heading">Add To Cart</h3>
  <hr>
</header>
<div class="card">
  <div class='row'>
  <div class='col-sm-6'>
    <img style="height: 350px" class="" src="{{ product.image.url }}" alt="">
  </div>
  <div class='col-sm-6'>
    <div class="card-body">
      <p class='lead'>{{product.name}}</p>
      <p class='lead'>${{product.price}}</p>
      <form method="POST" action=""> {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-outline-success'>Add to Cart</button>
      </form>
    </div>
  </div></div>
</div>
{% endblock %}

src/products/templates/products/product_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>Product Create</h1>
  <form method='POST' action='.' enctype='multipart/form-data'> {% csrf_token %}
    {{ form|crispy }}
    <button type='submit'>Create</button>
  </form>
{% endblock %}

src/products/templates/products/product_delete.html
{% extends 'base.html' %}

{% block content %}
<p class="lead text-muted text-center">Are you wanna remove this product?</p>
<form method="POST" action=""> {% csrf_token %}
  <div class="card" style="width: 500px; height: 500px; margin: auto">
    <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">{{product.name}}</h5>
      <div class="btn-group">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a href="/products" class="btn btn-outline-dark">No</a>
      </div>
    </div>
  </div>
</form>
{% endblock %}

src/products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}
<header class="mb-5">
  <h3 style="font-weight: bold" class="page-heading">Product Details</h3>
</header>
<br>
{% if product %}
<div style="display: grid; grid-template-columns: 1fr 1fr; grid-gap: 1rem;" class="card">
  <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title text-center">
      <strong>{{product.name}}</strong>
    </h5>
    <p class="card-text">
      ${{product.price}}
    </p>
    <p class="card-text">
      {{product.description}}
    </p>
    <p class="card-text">
      {{product.published_at}}
    </p>
    <hr>
    <p class="card-text">
      <strong>{{product.provide_by}}</strong>
    </p>
  </div>
</div>
{% else %}
<p class="lead text-muted">No products added yet..<p>
    {% endif %}
    {% endblock %}

src/products/templates/products/product_details.html
{% extends 'base.html' %}

{% block content %}
<header class="mb-5">
  <h3 style="font-weight: bold" class="page-heading">Product Details</h3>
</header>
<br>
{% if product %}
<div style="display: grid; grid-template-columns: 1fr 1fr; grid-gap: 1rem;" class="card">
  <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title text-center">
      <strong>{{product.name}}</strong>
    </h5>
    <p class="card-text">
      ${{product.price}}
    </p>
    <p class="card-text">
      {{product.description}}
    </p>
    <p class="card-text">
      {{product.published_at}}
    </p>
    <hr>
    <p class="card-text">
      <strong>{{product.provide_by}}</strong>
    </p>
  </div>
</div>
{% else %}
<p class="lead text-muted">No products added yet..<p>
    {% endif %}
    {% endblock %}

src/products/templates/products/product_list.html
{% extends 'base.html' %}

{% block content %}
<header class="mb-5">
  <h3 style="font-weight: bold" class="page-heading">Products</h3>
  <hr>
</header>
<div class="p-display-grid">
  {% if not products %}
  <p class="lead text-muted">No products added yet..<p>
      {% else %}
      {% for product in products %}
      <div class="card">
        <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">${{product.price}}</p>
          <div class="text-center">
            <div class="btn-group">
              <a class="btn btn-outline-primary m-2" style="text-decoration: none" href="{{product.get_like_url}}">
                <i class="fas fa-thumbs-up"></i>
                {% if product.like_set.all.count >= 1 %}
                {{ product.like_set.all|length }}
                {% endif %}
              </a>
              <a class="btn btn-outline-secondary m-2" href="{{product.get_unlike_url}}">
                <i class="fas fa-thumbs-down"></i>
              </a>
            </div>
            <br><br>
            <div class="btn-group">
              <a href="{{product.get_absolute_url}}" class="btn btn-outline-primary">Details</a>
              <a href="{{product.get_add_to_cart_url}}" class="btn btn-primary">Add to Cart</a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}
</div>
{% endblock %}

src/products/templates/products/product_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>Product Update</h1>
  <form method='POST' action='' enctype='multipart/form-data'> {% csrf_token %}
    {{ form|crispy }}
    <button type='submit'>Update</button>
  </form>
{% endblock %}