src/cart/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import CartListView, CartDeleteView

app_name = 'cart'
urlpatterns = [
    path(
        '',
        login_required(CartListView.as_view()),
        name='cart_list_view'
    ),
    path(
        '<int:pk>/delete/',
        login_required(CartDeleteView.as_view()),
        name='cart_item_delete_view'
    )
]

src/djecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('users/', include('users.urls')),
    path('profiles/', include('profiles.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/cart/models.py
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.db import models

from products.models import Product


class CartManager(models.Manager):
    def get_user_item(self, request_user, *args, **kwargs):
        return self.filter(user=request_user)

    def get_cart_item(self, product, user, *args, **kwargs):
        return self.get(product=product, user=user)


class Cart(models.Model):
    product = models.ForeignKey(
        Product,
        default=1,
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        default=1,
        on_delete=models.CASCADE
    )
    stocks = models.IntegerField(
        default=1
    )
    added_at = models.DateTimeField(
        auto_now_add=True
    )

    objects = CartManager()

src/templates/layouts/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">Dj E-Commerce</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="/dashboard">Dashboard</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="/profiles">Profiles</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/products">Products</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="/cart">
          <i class="fas fa-shopping-cart"></i>
          Cart
          {% if user.is_authenticated %}
            <span style="border-radius: 2rem;" class='bg-info text-light py-2 px-3'>{{ user.cart_set.all|length }}</span>
          {% endif %}
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i>
          User Management
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if user.is_authenticated %}
            {% if user.profile %}
            <a class="dropdown-item" href="{{user.profile.get_absolute_url}}">Profile</a>
            <a class="dropdown-item" href="{{user.profile.get_experience_url}}">Experiences</a>
            <a class="dropdown-item" href="{{user.profile.get_education_url}}">Educations</a>
            <div class="dropdown-divider"></div>
            {% endif %}
            <a class="dropdown-item" href="/users/sign-out">Logout</a>
          {% else %}
            <a class="dropdown-item" href="/users/sign-up">Sign Up</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/users/sign-in">Sign In</a>
          {% endif %}
        </div>
      </li>
    </ul>
  </div>
  </div>
</nav>